In [35]:
import pandas as pd

In [36]:
pd.__version__

'2.3.3'

In [37]:
emp  = pd.read_excel(r'C:\Users\ASUS\Downloads\Rawdata.xlsx')

In [38]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [39]:
id(emp)

2007136339360

In [40]:
emp.shape

(6, 6)

In [41]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [42]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [43]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [44]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [45]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [46]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [47]:
emp.isna()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [48]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [49]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [50]:
emp.dtypes

Name        object
Domain      object
Age         object
Location    object
Salary      object
Exp         object
dtype: object

# Data Cleaning

In [51]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [52]:
emp['Name']= emp['Name'].str.replace(r'\W','', regex=True) #non Word charac

In [53]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [54]:
emp['Domain']= emp['Domain'].str.replace(r'\W','', regex=True)

In [55]:
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [56]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [57]:
emp['Age']= emp['Age'].str.replace(r'\W','', regex=True)

In [58]:
emp['Age']

0    34years
1       45yr
2        NaN
3        NaN
4       67yr
5       55yr
Name: Age, dtype: object

In [59]:
emp['Age']= emp['Age'].str.extract('(\d+)')

In [60]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [61]:
emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [62]:
emp['Location']= emp['Location'].str.replace(r'\W','', regex=True)

In [63]:
emp['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [66]:
emp['Salary']= emp['Salary'].str.replace(r'\W','', regex=True)

In [67]:
emp['Salary']

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: object

In [68]:
emp

    Name       Domain  Age   Location Salary      Exp salary
0   Mike  Datascience   34     Mumbai   5000       2+   5000
1  Teddy      Testing   45  Bangalore  10000       <3  10000
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs  15000
3   Jane    Analytics  NaN   Hyderbad  20000      NaN  20000
4  Uttam   Statistics   67        NaN  30000  5+ year  30000
5    Kim          NLP   55      Delhi  60000      10+  60000

In [71]:
emp['Exp']= emp['Exp'].str.extract('(\d+)')

In [72]:
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: object

In [73]:
emp

    Name       Domain  Age   Location Salary  Exp salary
0   Mike  Datascience   34     Mumbai   5000    2   5000
1  Teddy      Testing   45  Bangalore  10000    3  10000
2   Umar  Dataanalyst  NaN        NaN  15000    4  15000
3   Jane    Analytics  NaN   Hyderbad  20000  NaN  20000
4  Uttam   Statistics   67        NaN  30000    5  30000
5    Kim          NLP   55      Delhi  60000   10  60000

In [74]:
clean_data = emp.copy()

In [75]:
clean_data

    Name       Domain  Age   Location Salary  Exp salary
0   Mike  Datascience   34     Mumbai   5000    2   5000
1  Teddy      Testing   45  Bangalore  10000    3  10000
2   Umar  Dataanalyst  NaN        NaN  15000    4  15000
3   Jane    Analytics  NaN   Hyderbad  20000  NaN  20000
4  Uttam   Statistics   67        NaN  30000    5  30000
5    Kim          NLP   55      Delhi  60000   10  60000